### ISSUE TITLE
dmd buildkite: undefined reference to `SSL_get_peer_certificate'

### ISSUE THREAD

**Issue by dkorpel** [sociomantic-tsunami/ocean#880]
Buildkite fails to build this project since a few days.

https://buildkite.com/dlang/dmd/builds/31722#0188a4d6-c74e-4e09-9200-26100bb7773c

```
/usr/bin/ld: /buildkite/builds/geod24-main-1/dlang/dmd/buildkite-ci-build/tmp/.rdmd-0/rdmd-allunittests.d-2D50FD84032A0BCEABD9AF8CB80B527E/objs/allunittests.o: in function `_D5ocean3net3ssl19SslClientConnectionQv19validateCertificateMFAxaZv':
/buildkite/builds/geod24-main-1/dlang/dmd/buildkite-ci-build/sociomantic-tsunami-ocean/./src/ocean/net/ssl/SslClientConnection.d:371: undefined reference to `SSL_get_peer_certificate'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

Possibly introduced by https://github.com/sociomantic-tsunami/ocean/commit/a8f85d006e59a2cf2a7d4956051e4ae7d883343d

**Comment by Geod24** [comment]
The runner needed a re-deployment AFAIR, master is green now.
