### ISSUE TITLE
[D2] Exact type comparison of delegate for StructContext is a Bad Idea

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#492]
Got the following error:

```
./submodules/ocean/src/ocean/util/container/pool/StructPool.d(82): Error: static assert  "VersionContext.reset() must be 'void reset()'"
```

Added a bit of debugging:
```diff
diff --git a/src/ocean/util/container/pool/StructPool.d b/src/ocean/util/container/pool/StructPool.d
index f6b0dbfe..cbe07b4c 100644
--- a/src/ocean/util/container/pool/StructPool.d
+++ b/src/ocean/util/container/pool/StructPool.d
@@ -82,7 +82,7 @@ public class StructPool ( T ) : IAggregatePool!(T)
             static assert(
                    is(typeof(&T.init.reset) == void delegate())
                 || is(typeof(&T.init.reset) == void function()),
-                T.stringof ~ ".reset() must be 'void reset()'"
+                   T.stringof ~ ".reset() must be 'void reset()', not: " ~ typeof(&T.init.reset).stringof
             );
 
             this.fromItem(item).reset();
```

And:
```
./submodules/ocean/src/ocean/util/container/pool/StructPool.d(82): Error: static assert  "VersionContext.reset() must be 'void reset()', not: void delegate() pure nothrow @nogc @safe"
```

This happens because the struct is templated (to be precise, it's nested within a template).
Introduced by https://github.com/sociomantic-tsunami/ocean/commit/5c0c6eb740d31ed453bfaaa1abdd165f8df44d5e because `hasMethod` did the following:
https://github.com/sociomantic-tsunami/ocean/blob/c704d282612decfe485c7fd69c1f4bc13d90d6bd/src/ocean/core/Traits.d#L1281-L1284

Which is closer to `is(X : Y)` than `is(X == Y)`

**Comment by mathias-lang-sociomantic** [comment]
CC @mihails-strasuns-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Regression in v4, right?

**Comment by mathias-lang-sociomantic** [comment]
Genau

**Comment by nemanja-boric-sociomantic** [comment]
Fixed in #493
